### ISSUE TITLE
Failed to load 20.2.0

### ISSUE THREAD

**Issue by ghost** [pcwii/kodi-skill#11]
Trying to get this plugin working, installed it, rebooted picroft and on startup it says "communicate_load_status:286" "failed to load". It's also not showing in my account settings online. I think it was working on picroft 19 but can't seem to go back to that and it just keeps auto updating me. I'm guessing the new update broke something?

**Comment by scottsweb** [comment]
Also have some trouble with loading this skill in `20.2.x`:

```
tail /var/log/mycroft/skills.log -n 1000 | grep kodi 
2020-03-23 13:43:12.439 | INFO     |  1905 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: kodi-skill.pcwii
2020-03-23 13:43:14.441 | INFO     |  1905 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/kodi-skill.pcwii/settings.json
  File "/opt/mycroft/skills/kodi-skill.pcwii/__init__.py", line 64, in initialize
2020-03-23 13:43:15.504 | ERROR    |  1905 | mycroft.skills.skill_loader:_communicate_load_status:286 | Skill kodi-skill.pcwii failed to load
2020-03-23 13:48:44.112 | INFO     |  3288 | mycroft.skills.skill_loader:load:114 | ATTEMPTING TO LOAD SKILL: kodi-skill.pcwii
2020-03-23 13:48:47.535 | INFO     |  3288 | mycroft.skills.settings:get_local_settings:78 | /opt/mycroft/skills/kodi-skill.pcwii/settings.json
  File "/opt/mycroft/skills/kodi-skill.pcwii/__init__.py", line 64, in initialize
```

The settings.json file doesn't exist after fresh install so perhaps that is the problem. I will see if I can get it started.

**Comment by scottsweb** [comment]
I created a faked `settings.json` file and now get this error:

``` 
mycroft.skills.skill_loader:_create_skill_instance:249 | Skill initialization failed with AttributeError("'dict' object has no attribute 'set_changed_callback'")
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/skill_loader.py", line 243, in _create_skill_instance
    self.instance.initialize()
  File "/opt/mycroft/skills/kodi-skill.pcwii/__init__.py", line 64, in initialize
    self.settings.set_changed_callback(self.on_websettings_changed)
AttributeError: 'dict' object has no attribute 'set_changed_callback'
```

So there has perhaps been a slight API change for skills.

**Comment by Nyndroth** [comment]
I am experiencing the same problem. If you need someone to test any new developments, let me know.

**Comment by pcwii** [comment]
@Nyndroth, @scottsweb, @tempuser0012 Thanks for the info. There was a breaking change in 20.2 that changed the syntax of the 'set_changed_callback' (basically a notification if the web settings are updated. I have corrected this and it should work as expected.

**Comment by scottsweb** [comment]
Thanks, will give it a test.
